# Generated by Django 3.1.6 on 2021-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deposit',
            field=models.PositiveIntegerField(default=500, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
    ]
